### ISSUE TITLE
EPIC: Set-up and preliminary analysis

### ISSUE THREAD

**Issue by Piiit** [idm-suedtirol/bdp-commons#1]
Project: Air Quality

Assigned: Patrick Bertolla

- [ ] As a developer, I want to push my HelloWorld project on a github repository managed by IDM - Patrick Bertolla
- [ ] As a developer, I want to see my HelloWorld integrated in the testing CI pipeline of IDM - Patrick Bertolla

- [ ] As a developer, I want to have the bdp-core installed locally to start testing the data collector code
- [ ] As a developer, I want to have my IDE configured and the HelloWorld project correctly running
- [ ] As a developer, I need to understand in detail the ODH architecture and the data exchange details 
- [ ] As a developer, I need to study reference Data Collectors implementation in order to understand how to write the new software
